[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
monad_testnet = "${MONAD_RPC_URL}"

[etherscan]
# Sourcify kullanıldığı için etherscan key gerekmez
monad_testnet = { key = "verifyonly", url = "https://sourcify.dev/server" }
